services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sqladmin
    ports:
      - '5432:5432'
